apiVersion: v2
name: fastapi-celery
description: FastAPI + Celery + Redis + Beat + Flower
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: 19.0.2
    repository: https://charts.bitnami.com/bitnami
