version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A app.celery_app beat --loglevel=info
    depends_on:
      - redis

  flower:
    image: mher/flower:2.0
    command: celery --broker=redis://redis:6379/0 flower
    ports:
      - "5555:5555"
    depends_on:
      - redis

