apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-celery.fullname" . }}-api
  labels:
    {{- include "fastapi-celery.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "fastapi-celery.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8000
