apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi-celery.fullname" . }}-api
  labels:
    {{- include "fastapi-celery.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- include "fastapi-celery.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "fastapi-celery.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      {{- include "fastapi-celery.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: api
          image: "{{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}"
          imagePullPolicy: {{ .Values.images.api.pullPolicy }}
          command: ["uvicorn"]
          args:
            - app.main:app
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          env:
            - name: CELERY_BROKER_URL
              value: redis://{{ include "fastapi-celery.fullname" . }}-redis:6379/0
            - name: CELERY_RESULT_BACKEND
              value: redis://{{ include "fastapi-celery.fullname" . }}-redis:6379/1
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
