apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi-celery.fullname" . }}-worker
  labels:
    {{- include "fastapi-celery.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "fastapi-celery.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "fastapi-celery.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- include "fastapi-celery.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: worker
          image: "{{ .Values.images.worker.repository }}:{{ .Values.images.worker.tag }}"
          imagePullPolicy: {{ .Values.images.worker.pullPolicy }}
          command: ["celery"]
          args:
            - -A
            - app.celery_app
            - worker
            - --loglevel=info
          env:
            - name: CELERY_BROKER_URL
              value: redis://{{ include "fastapi-celery.fullname" . }}-redis:6379/0
            - name: CELERY_RESULT_BACKEND
              value: redis://{{ include "fastapi-celery.fullname" . }}-redis:6379/1
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
